---
title: "Análise das referências"
format: 
   dashboard:
      orientation: columns
      number-sections: false
server: shiny
---

```{r}
library(RefManageR)

library(tidyverse)

library(shiny)

library(plotly)
```


```{r}
bib <- RefManageR::ReadBib("library.bib", check = FALSE) |> 
   tibble::as_tibble()
```

```{r}
theme_set(theme_bw() +
            theme(axis.text = element_text(color = "black", size = 15),
                  axis.title = element_text(color = "black", size = 15),
                  legend.text = element_text(color = "black", size = 15),
                  legend.title = element_text(color = "black", size = 15),
                  panel.border = element_rect(color = "black", linewidth = 1)))
```

```{r, echo=FALSE}
quantidades <- bib |> 
   dplyr::summarise(n = dplyr::n(),
                    .by = bibtype)
```

# Artigos

## {.sidebar}

```{r}
sliderInput("Ano", 
            "Ano", 
            min = bib$year |> as.numeric() |> na.omit() |> min(), 
            max = bib$year |> as.numeric() |> na.omit() |> max(),
            value = bib |> nrow(), 
            step = 15, round=0)
```

## Column {width = "10%"}

```{r}
#| content: valuebox
#| title: "Número de artigos"
list(icon = "book",
     color = "primary",
     value = quantidades |> 
        dplyr::filter(bibtype == "Article") |> 
        dplyr::pull(n))
```

## Column

### Row {.tabset}

::: {.card title = "Quantidade de artigos por ano"}
```{r}
anos_abrangecia <- bib |>
   dplyr::filter(bibtype == "Article") |> 
   dplyr::pull(year) |> 
   na.omit() |> 
   range()

ggplt1 <- bib |>
   dplyr::filter(bibtype == "Article") |> 
   dplyr::summarise(quantidade = dplyr::n(),
                    .by = year) |>
   dplyr::mutate(Ano = year |> as.numeric()) |>
   ggplot(aes(Ano, quantidade)) +
   geom_line(linewidth = 1) +
   labs(x = "Ano",
        y = "Quantidade de artigos") +
   scale_x_continuous(breaks = seq(1910, 2026, 15)) +
   theme_bw() +
   theme(axis.text = element_text(color = "black", size = 15),
         axis.title = element_text(color = "black", size = 15),
         legend.text = element_text(color = "black", size = 15),
         legend.title = element_text(color = "black", size = 15),
         panel.border = element_rect(color = "black", linewidth = 1))

plotly::ggplotly(ggplt1, tooltip = c("x", "y")) |> 
   layout(xaxis = list(rangeslider = list(visible = TRUE), 
                       range = anos_abrangecia,
                       type = "date")) 
```
:::

# Capítulos e livros

# Revistas

# Áreas
